clienteGestionDeTurnos/MVC/Models/Administrador.cs
namespace MVC.Models
{
    public class Administrador
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Dni { get; set; }
        public DateTime fechaNacimiento { get; set; }
        public string Calle { get; set; }
        public int Altura { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string confirPass { get; set; }  

    }
}

clienteGestionDeTurnos/MVC/Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using Newtonsoft.Json;
using System.Runtime.Intrinsics.Arm;
using System.Text;


namespace MVC.Controllers
{
    public class AdministradorController : Controller
    {
        private readonly HttpClient _httpClient;

        public AdministradorController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7147/administradores");
        }

        public async Task<IActionResult> Index(int dni)
        {
            if (dni != 0 )
            {
                var resp = await _httpClient.GetAsync($"administradores/buscar{dni}");

                if (resp.IsSuccessStatusCode)
                {
                    var content = await resp.Content.ReadAsStringAsync();
                    var administrador = JsonConvert.DeserializeObject<Administrador>(content);

                    

                    return View("Index", new List<Administrador>(new Administrador[] {administrador} ));
                }

            }
            else
            {
                var response = await _httpClient.GetAsync("administradores/listado");

                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    var administradores = JsonConvert.DeserializeObject<IEnumerable<Administrador>>(content);


                    return View("Index", administradores);
                }
           
            }

            return View (new List<Administrador>());
        }

   

        [HttpGet]
        public async Task<IActionResult> Editar(int idAdmiMod)
        {
            Administrador administrador;

            try
            {


                // Hace la solicitud GET a la API
                var response = await _httpClient.GetAsync($"administradores/buscar{idAdmiMod}");

                if (response.IsSuccessStatusCode)
                {
                    // Si la solicitud es exitosa, deserializa el contenido a un objeto Administrador
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    administrador = JsonConvert.DeserializeObject<Administrador>(jsonResponse);
                }
                else
                {
                    // Manejo de errores si la solicitud no es exitosa
                    return BadRequest("Error al obtener el administrador desde la API.");
                }
            }
            catch (Exception ex)
            {
                // Manejo de excepciones
                return BadRequest(ex.Message);
            }

            // Retorna la vista de modificación con el modelo del administrador
            return View(administrador);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Administrador adm)
        {

            var jsonData = JsonConvert.SerializeObject(adm);

            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync($"administradores/update/datosPersonales{adm.Id}", content);

            if (response.IsSuccessStatusCode)
            {
                // Manejar la respuesta exitosa
                var result = await response.Content.ReadAsStringAsync();
                return Content($"Éxito: {result}");

                //return RedirectToAction("Index");   // volver al index
            }
            else
            {
                var resultNeg = await response.Content.ReadAsStringAsync();
                return Content($"Error: {resultNeg}");


            }    
            
            //ModelState.AddModelError(string.Empty, "Error al crear un nuevo administrador.");
            
            //if (ModelState.IsValid)
            //{
            //    try
            //    {


            //        // Crear el contenido para el cuerpo de la solicitud usando directamente el objeto administrador
            //        var content = new StringContent(JsonConvert.SerializeObject(administrador), Encoding.UTF8, "application/json");

            //        // Hace la solicitud PUT a la API
            //        var response = await _httpClient.PostAsync("https://localhost:7147/administradores/update/datosPersonales", content);

            //        if (response.IsSuccessStatusCode)
            //        {
            //            return RedirectToAction("Index");
            //        }
            //        else
            //        {
            //            ModelState.AddModelError(string.Empty, "Error al actualizar los datos del administrador.");
            //        }
            //    }
            //    catch (Exception ex)
            //    {
            //        ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
            //    }
            //}

            //return View(administrador);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Administrador adm)
        {
            var jsonData = JsonConvert.SerializeObject(adm);

            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("https://localhost:7147/administradores/add", content);

            if (response.IsSuccessStatusCode)
            {
                // Manejar la respuesta exitosa
                var result = await response.Content.ReadAsStringAsync();
                return Content($"Éxito: {result}");

                //return RedirectToAction("Index");   // volver al index
            }
            else
            {
                var resultNeg = await response.Content.ReadAsStringAsync();
                return Content($"Error: {resultNeg}");

                //ModelState.AddModelError(string.Empty, "Error al crear un nuevo administrador.");
            }

        }
     
    }
}

clienteGestionDeTurnos/MVC/Views/Administrador/Create.cshtml
@model Administrador;

@{
    ViewData["Title"] = "Crear nuevo Administrador";
}

<h1>Crear nuevo Administrador</h1>

<form asp-action="Create" method="post">

    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellido"></label>
        <input asp-for="Apellido" class="form-control" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Dni"></label>
        <input asp-for="Dni" class="form-control" />
        <span asp-validation-for="Dni" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="fechaNacimiento"></label>
        <input asp-for="fechaNacimiento" class="form-control" type="date" />
        <span asp-validation-for="fechaNacimiento" class="text-danger"></span>
    </div>
    <div class="form-group">
        <labvel asp-for="Calle"></labvel>
        <input asp-for="Calle" class="form-control" />
        <span asp-validation-for="Calle" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Altura"></label>
        <input asp-for="Altura" class="form-control" />
        <span asp-validation-for="Altura" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" type="email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" type="password" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="confirPass"></label>
        <input asp-for="confirPass" class="form-control" type="password" />
        <span asp-validation-for="confirPass" class="text-danger"></span>
    </div>
    <button type="submit"  class="btn btn-primary">Crear</button>
    <a asp-action="Index" asp-controller="Administrador" class="btn btn-secondary">Volver a la lista</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

clienteGestionDeTurnos/MVC/Views/Administrador/Editar.cshtml
@model Administrador

@{
    ViewData["Title"] = "Actualizar datos personales";

}

<h1>Actualizar datos personales Administrador</h1>

<form asp-action="Update" method="post">
    <!-- Campo oculto para el ID -->
    <input type="hidden" name="Id" value="@Model.Id" />

    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" readonly />
        <span asp-validation-for="Id" class="text-danger"></span>

    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Apellido"></label>
        <input asp-for="Apellido" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Dni"></label>
        <input asp-for="Dni" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="fechaNacimiento"></label>
        <input asp-for="fechaNacimiento" class="form-control" type="date" />
    </div>
    <div class="form-group">
        <label asp-for="Calle"></label>
        <input asp-for="Calle" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Altura"></label>
        <input asp-for="Altura" class="form-control" />
    </div>

  
    <button type="submit" class="btn btn-primary">Guardar cambios</button>
</form>

clienteGestionDeTurnos/MVC/Views/Administrador/Index.cshtml
@model IEnumerable<Administrador>
@{
    ViewData["Title"] = "Lista de Administradores";
}

<h1>Lista de Administradores</h1>

<p>
    <a asp-controller="Administrador" asp-action="Create" class="btn btn-primary">Crear Nuevo</a>
</p>

<form asp-controller="Administrador" asp-action="Index" method="get">
    <input type="text" name="dni" placeholder="Ingrese DNI del administrador"></input>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>


<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>DNI</th>
            <th>Fecha de Nacimiento</th>
            <th>Calle</th>
            <th>Altura</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var admin in Model)
        {
            <tr>
                <td>@admin.Id</td>
                <td>@admin.Nombre</td>
                <td>@admin.Apellido</td>
                <td>@admin.Dni</td>
                <td>@admin.fechaNacimiento.ToString("dd/MM/yyyy")</td>
                <td>@admin.Calle</td>
                <td>@admin.Altura</td>


                <td>
                    <!-- Botón de actualizar -->
                    <a href="@Url.Action("Editar", new {idAdmiMod = admin.Id })" class="btn btn-primary">Actualizar</a>
                </td>

            </tr>
        }
    </tbody>
</table>